import type { Meta, StoryObj } from '@storybook/react-vite';
import { Doc, Section, Card } from './Docs';
function DecisionsPage() { return <Doc eyebrow="Decisions & handoff" title="Make the tradeoffs visible." intro="A design system is also a record of intent: what is consistent, what is still evolving, and how to change it responsibly.">
 <Section title="Design decisions"><div className="grid"><Card title="Desktop density"><p>A 13 px default and compact controls serve a content-heavy library. Larger touch targets and readable secondary content still need contextual review.</p></Card><Card title="Semantic theming"><p>Components consume role-based CSS variables. Theme and accent choices change their values without requiring separate component implementations.</p></Card><Card title="Two kinds of progress"><p>Wishlist, Backlog, Playing and Played describe a play journey. Completed, Mastered, Abandoned and Shelved describe outcomes. Ratings express an independent personal judgment.</p></Card></div></Section>
 <Section title="Open implementation gaps"><div className="stack"><Card title="Status language"><p>CoverCardMetadata maps Played to Completed. Align the label with the domain model before using the system as a claim of complete consistency.</p><code>src/components/CoverCard/CoverCardMetadata.tsx</code></Card><Card title="Contrast across appearances"><p>Tertiary text is low contrast in both themes. Light-mode secondary text also needs review. Use the Accessibility panel and inspect real surface combinations; automated checks are not a manual screen-reader review.</p><code>src/styles/theme.css</code></Card><Card title="Unset ratings"><p>The slider exposes a minimum of 0.5 but reports 0 when unset. Define an explicit unrated state and validate its accessible announcement.</p><code>src/components/ui/StarRating.tsx</code></Card><Card title="Tag and filter keyboard access"><p>Tag removal needs a specific accessible name. Tag suggestions need a complete keyboard interaction model; filter facets currently use clickable divs. These stories expose the current behavior.</p><code>src/components/ui/TagSelect.tsx · src/components/features/FilterBar.tsx</code></Card><Card title="Motion"><p>The button spinner is now defined in Button.css. Skeleton pulse and other animation still need a reduced-motion review.</p><code>src/components/ui/Button.tsx · src/components/ui/Skeleton.tsx</code></Card></div></Section>
 <Section title="A lightweight change process"><ol><li>Describe the user problem and identify the shared component or token.</li><li>Update the implementation and Figma counterpart together.</li><li>Review every affected state in light and dark, plus relevant accent choices.</li><li>Exercise keyboard, loading, empty and error behavior in Storybook.</li><li>Record the change and document any remaining gaps.</li></ol></Section>
 <Section title="Portfolio framing"><p>This library formalizes a solo-built product. Discuss the reasons behind component boundaries, the implementation constraints and what you would test next. No adoption metrics, user outcomes or delivery improvements are claimed without evidence.</p></Section>
 </Doc>; }
const meta = { title: 'Decisions/System stewardship', component: DecisionsPage, parameters: { layout: 'fullscreen', controls: { disable: true } } } satisfies Meta<typeof DecisionsPage>;
export default meta;
export const Overview: StoryObj<typeof meta> = {};
